### ISSUE TITLE
Performance seems inadequate

### ISSUE THREAD

**Issue by Alexdc-12** [Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container#16]
Hi
When this container is installed and being used in a Synapse environment, pulling data from a DB2 database, transfer times are really slow! 700k records which is around 3GB of data takes 9 1/2 hrs to transfer. 
If we take docker out of the equation and install the SHIR directly on the windows server the performance issues are gone. 

I am told Docker is setup to use Default process isolation mode, which should allow docker to consume as much of the hosts resources? 

I also note that the stats are blank/static within the Integration Runtime monitor when using Docker, again when direct on Server they work. Memory is always 0MB, CPU stuck at 50%, Network always 0
![image](https://github.com/Azure/Azure-Data-Factory-Integration-Runtime-in-Windows-Container/assets/48382348/3c1a5b69-7067-4f03-b55d-2b5b49d651f4)

As far as i am aware there is no other way to install multiple SHIRs on a VM for Synapse so i really need to get this working!

**Comment by byran77** [comment]
Hi @Alexdc-12 
the monitor for SHIR in container is a known issue now due to docker limitation, and thus the data on the portal is not accurate. 
could you please provide the ActivityID of the slow copy for us to help troubleshoot? thanks!

**Comment by Alexdc-12** [comment]
> Hi @Alexdc-12 the monitor for SHIR in container is a known issue now due to docker limitation, and thus the data on the portal is not accurate. could you please provide the ActivityID of the slow copy for us to help troubleshoot? thanks!

Here is an ActivityID of one of the slow copies however, 6854ee8d-13c4-47be-9279-18d86c00c6fa

**Comment by byran77** [comment]
> > Hi @Alexdc-12 the monitor for SHIR in container is a known issue now due to docker limitation, and thus the data on the portal is not accurate. could you please provide the ActivityID of the slow copy for us to help troubleshoot? thanks!
> 
> Here is an ActivityID of one of the slow copies however, 6854ee8d-13c4-47be-9279-18d86c00c6fa

glad to hear it finally works well. With the ActivityID we double-checked that there are no running errors on IR and thus the problem is transient. If the abnormal performance reduction occurs frequently, please kindly to raise an Azure Support Ticket for more helps.

We are working on root problem verification of the monitor issue, and will update it on [Microsoft Learn page](https://learn.microsoft.com/en-us/azure/data-factory/how-to-run-self-hosted-integration-runtime-in-windows-container) **Limitations**.

Thanks!
